"""Add negotiation_offers table

Revision ID: f56e4eb602fe
Revises: 17b15e6608ca
Create Date: 2026-09-13 22:47:54.102108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56e4eb602fe'
down_revision: Union[str, Sequence[str], None] = '17b15e6608ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('original_product_id', sa.Integer(), nullable=False),
    sa.Column('alternative_product_id', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['original_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_offers_id'), 'negotiation_offers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_offers_id'), table_name='negotiation_offers')
    op.drop_table('negotiation_offers')
    # ### end Alembic commands ###
